from setuptools import setup, find_packages
setup(
    name='jenkinsapi',
    version='0.1',
    license='Apache-2.0',
    packages=find_packages(),
    include_package_data=True,
    install_requires=[
        'click==6.7',
        'pathlib2',
        'xmltodict==0.11.0',
        'jenkins-webapi==0.5.3'
    ],
    entry_points='''
        [console_scripts]
        jenkins-cmd=jenkinsapi.scripts.jenkins_cli:jenkins
        serverlist=jenkinsapi.scripts.serverlist:main
    ''',
)
